### PR TITLE
Update bb95, add Quiet Goodnight XL, Photon, AAM XL

### PR DESCRIPTION
**Pull request by ResidentChief**

### CODE REVIEW

**Review by tazlin — CHANGES_REQUESTED** [review]
Are we absolutely positive we want to change in-place `BB95 Furry Mix`? This model may have niche appeal, but among those to whom it *does* appeal, I suspect they may not take kindly to this model changing suddenly. Has this been discussed in the server at all?

**Comment by db0** [comment]
It's just a new version which should be an improvement, no?

**Comment by tazlin** [comment]
> It's just a new version which should be an improvement, no?

If we are changing the model, it's changing. "improvement" in art is entirely subjective. We've litigated this exact issue in the past with deliberate, and users overwhelmingly disagreed with changing Deliberate to 3.0 (which, I might add, 3.0 is not *nearly* as popular). 

I was then, and I am now, strongly against changing very popular (in terms of usage) models without at least asking the community first.

**Comment by db0** [comment]
Eh, I'm of the opinion for this sort of low-stakes, better to ask for forgiveness that permission. If people complain, we can just re-add the old model as another version. I don't want to keep reducing my momentum on constant what ifs.

**Comment by tazlin** [comment]
This is not low stakes for a certain amount of users.

Last time you said you'd put these sort of points of disagreement up to community vote - I respectfully ask that we do that here.

**Comment by ResidentChief** [comment]
I do remember saying Id do comparions but bb95 isnt a top 5 model by
generations (and about a fifth as many gens as the top model) and Im not
sure how far you want to go before you have to do a comparison for any
change??

Ill revert the update and just add the 4 new ones

**Review by db0 — APPROVED** [review]
The b95 model changes have been reverted

**Review by tazlin — APPROVED** [review]

**Pull request merged**
