### PR TITLE
feat: Pony Realism

### PR DESCRIPTION
**Pull request by Unit1208**
This PR adds [Pony Realism](https://civitai.com/models/372465?modelVersionId=534642), a realistic Pony model. It appears to work fine, at least on my Kaggle worker.

### CODE REVIEW

**Comment by tazlin** [comment]
Is the pruned version of this model? I see it says size full in the civitai url. Sometimes there is a pruned version which is significantly smaller in size.

**Comment by Unit1208** [comment]
No, there doesn't appear to be one for this model

**Comment by arcaria** [comment]
It's only 6.62 gb, like most other xl models.
Also, I've noticed that civitai's links seem to be unnecessaryly large and unhelpful, "https://civitai.com/api/download/models/534642?type=Model&format=SafeTensor&size=full&fp=fp16" can be reduced to "https://civitai.com/api/download/models/534642", that is the only part that really matters

**Comment by tazlin** [comment]
> It's only 6.62 gb, like most other xl models. Also, I've noticed that civitai's links seem to be unnecessarily large and unhelpful, "https://civitai.com/api/download/models/534642?type=Model&format=SafeTensor&size=full&fp=fp16" can be reduced to "https://civitai.com/api/download/models/534642", that is the only part that really matters

This breaks in the situation that the author adds a new model version which gets selected as the new default from the unqualified link (the link with out the bit after the ?), at which point the worker will start downloading the wrong version, attempt to validate it, fail, delete it, redownload it, fail again and so on.

**Comment by arcaria** [comment]
Sorry, I don't get what you mean there. A new version of a model on civitai will have a new version id so the download link will be different, right?

**Comment by tazlin** [comment]
> Sorry, I don't get what you mean there. A new version of a model on civitai will have a new version id so the download link will be different, right?

No the number might not change; that's why the download link has the extra information. Its not unnecessary. Its required to distinguish pruned/unpruned or precision downloads.

**Comment by tazlin** [comment]
The problem here is the nuanced use of the word 'version'. I also used it confusingly. CivitAI doesn't consider different file formats or pruned/unpruned choices to be different if its for the same model 'version'. Version 2.1 of a model might have safetensors or pickle, fp8 or fp16 but still be all the same 'version'. At least, this is the way it was in the past because we had issues surrounding exactly this, which is when I saw the issue with the worker failing eternally that I mentioned.

**Comment by arcaria** [comment]
Hmm, ok, I saw that just now with some embeddings, but after looking through some models, I think most model creators/uploaders stick to a single file per version. For instance, the Flux model we are using, https://civitai.com/models/637170?modelVersionId=714945, seems to do this, with every version using a single file.
There might be some use to keeping the whole link then, but I've been stripping that part when running my workers and I've had no issues so far

**Comment by tazlin** [comment]
Just as a matter of convention, I'm asking we use the full URL. This file is primarily read by computers, it could be 10 characters or 1000 and it shouldn't end up mattering to any end users. We shouldn't leave out information when it *only* improves specificity and when leaving it out *could* open us up to problems.

**Review by tazlin — APPROVED** [review]

**Comment by tazlin** [comment]
Note that it takes approximately 1 hour for the AI-Horde to pick up the new model.

**Pull request merged**
